/**
 * Generated by orval 🍺
 * Do not edit manually.
 * sloppr | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  GetApiAiIngredientExtractionChallengeParams
} from '../model';

import { customInstance } from '.././custom-instance';








@Injectable({ providedIn: 'root' })
export class AiIngredientExtractionService {
  private readonly http = inject(HttpClient);
 getApiAiIngredientExtractionChallenge<TData = void>(
    params?: GetApiAiIngredientExtractionChallengeParams,
 ) {
      return customInstance<TData>(
      {url: `/api/AiIngredientExtraction/challenge`, method: 'GET',
        params: (() => {

  const filteredParams: Record<string, string | number | boolean | Array<string | number | boolean>> = {};
  for (const [key, value] of Object.entries(params ?? {})) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
})()
    },
      this.http,
      );
    }
  };

export type GetApiAiIngredientExtractionChallengeClientResult = NonNullable<void>
