/**
 * Generated by orval 🍺
 * Do not edit manually.
 * sloppr | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  AiModel,
  AiModelDTO,
  AiModelMinimalDTO
} from '../model';

import { customInstance } from '.././custom-instance';






export type GetApiAiModelsAccept = typeof GetApiAiModelsAccept[keyof typeof GetApiAiModelsAccept];

export const GetApiAiModelsAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type PostApiAiModelsAccept = typeof PostApiAiModelsAccept[keyof typeof PostApiAiModelsAccept];

export const PostApiAiModelsAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type GetApiAiModelsInactiveAccept = typeof GetApiAiModelsInactiveAccept[keyof typeof GetApiAiModelsInactiveAccept];

export const GetApiAiModelsInactiveAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type GetApiAiModelsIdAccept = typeof GetApiAiModelsIdAccept[keyof typeof GetApiAiModelsIdAccept];

export const GetApiAiModelsIdAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type PostApiAiModelsBatchAccept = typeof PostApiAiModelsBatchAccept[keyof typeof PostApiAiModelsBatchAccept];

export const PostApiAiModelsBatchAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

@Injectable({ providedIn: 'root' })
export class AiModelsService {
  private readonly http = inject(HttpClient);
 getApiAiModels<TData = AiModel[]>(

 ) {
      return customInstance<TData>(
      {url: `/api/AiModels`, method: 'GET'
    },
      this.http,
      );
    }
   postApiAiModels<TData = AiModel>(
    aiModel: AiModel,
 ) {
      return customInstance<TData>(
      {url: `/api/AiModels`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aiModel
    },
      this.http,
      );
    }
   getApiAiModelsInactive<TData = AiModel[]>(

 ) {
      return customInstance<TData>(
      {url: `/api/AiModels/inactive`, method: 'GET'
    },
      this.http,
      );
    }
   getApiAiModelsId<TData = AiModelDTO>(
    id: number | string,
 ) {
      return customInstance<TData>(
      {url: `/api/AiModels/${id}`, method: 'GET'
    },
      this.http,
      );
    }
   putApiAiModelsId<TData = void>(
    id: number | string,
    aiModel: AiModel,
 ) {
      return customInstance<TData>(
      {url: `/api/AiModels/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: aiModel
    },
      this.http,
      );
    }
   deleteApiAiModelsId<TData = void>(
    id: number | string,
 ) {
      return customInstance<TData>(
      {url: `/api/AiModels/${id}`, method: 'DELETE'
    },
      this.http,
      );
    }
   postApiAiModelsBatch<TData = number | string>(
    aiModelMinimalDTO: AiModelMinimalDTO[],
 ) {
      return customInstance<TData>(
      {url: `/api/AiModels/batch`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aiModelMinimalDTO
    },
      this.http,
      );
    }
  };

