/**
 * Generated by orval 🍺
 * Do not edit manually.
 * sloppr | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  KeyIngredient,
  KeyIngredientDTO
} from '../model';

import { customInstance } from '.././custom-instance';






export type GetApiKeyIngredientsAccept = typeof GetApiKeyIngredientsAccept[keyof typeof GetApiKeyIngredientsAccept];

export const GetApiKeyIngredientsAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type PostApiKeyIngredientsAccept = typeof PostApiKeyIngredientsAccept[keyof typeof PostApiKeyIngredientsAccept];

export const PostApiKeyIngredientsAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type GetApiKeyIngredientsIdAccept = typeof GetApiKeyIngredientsIdAccept[keyof typeof GetApiKeyIngredientsIdAccept];

export const GetApiKeyIngredientsIdAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

@Injectable({ providedIn: 'root' })
export class KeyIngredientsService {
  private readonly http = inject(HttpClient);
 getApiKeyIngredients<TData = KeyIngredient[]>(

 ) {
      return customInstance<TData>(
      {url: `/api/KeyIngredients`, method: 'GET'
    },
      this.http,
      );
    }
   postApiKeyIngredients<TData = KeyIngredient>(
    keyIngredient: KeyIngredient,
 ) {
      return customInstance<TData>(
      {url: `/api/KeyIngredients`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: keyIngredient
    },
      this.http,
      );
    }
   getApiKeyIngredientsId<TData = KeyIngredientDTO>(
    id: number | string,
 ) {
      return customInstance<TData>(
      {url: `/api/KeyIngredients/${id}`, method: 'GET'
    },
      this.http,
      );
    }
   putApiKeyIngredientsId<TData = void>(
    id: number | string,
    keyIngredient: KeyIngredient,
 ) {
      return customInstance<TData>(
      {url: `/api/KeyIngredients/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: keyIngredient
    },
      this.http,
      );
    }
   deleteApiKeyIngredientsId<TData = void>(
    id: number | string,
 ) {
      return customInstance<TData>(
      {url: `/api/KeyIngredients/${id}`, method: 'DELETE'
    },
      this.http,
      );
    }
  };

