/**
 * Generated by orval 🍺
 * Do not edit manually.
 * sloppr | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  AiModelMinimalDTO,
  AiProvider,
  AiProviderDTO,
  AiProviderHealthDTO,
  GetApiAiProvidersHealthParams
} from '../model';

import { customInstance } from '.././custom-instance';






export type GetApiAiProvidersAccept = typeof GetApiAiProvidersAccept[keyof typeof GetApiAiProvidersAccept];

export const GetApiAiProvidersAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type PostApiAiProvidersAccept = typeof PostApiAiProvidersAccept[keyof typeof PostApiAiProvidersAccept];

export const PostApiAiProvidersAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type GetApiAiProvidersInactiveAccept = typeof GetApiAiProvidersInactiveAccept[keyof typeof GetApiAiProvidersInactiveAccept];

export const GetApiAiProvidersInactiveAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type GetApiAiProvidersIdAccept = typeof GetApiAiProvidersIdAccept[keyof typeof GetApiAiProvidersIdAccept];

export const GetApiAiProvidersIdAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type GetApiAiProvidersIdDiscoverModelsAccept = typeof GetApiAiProvidersIdDiscoverModelsAccept[keyof typeof GetApiAiProvidersIdDiscoverModelsAccept];

export const GetApiAiProvidersIdDiscoverModelsAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type GetApiAiProvidersHealthAccept = typeof GetApiAiProvidersHealthAccept[keyof typeof GetApiAiProvidersHealthAccept];

export const GetApiAiProvidersHealthAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type PostApiAiProvidersIdHealthAccept = typeof PostApiAiProvidersIdHealthAccept[keyof typeof PostApiAiProvidersIdHealthAccept];

export const PostApiAiProvidersIdHealthAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

@Injectable({ providedIn: 'root' })
export class AiProvidersService {
  private readonly http = inject(HttpClient);
 getApiAiProviders<TData = AiProvider[]>(

 ) {
      return customInstance<TData>(
      {url: `/api/AiProviders`, method: 'GET'
    },
      this.http,
      );
    }
   postApiAiProviders<TData = AiProvider>(
    aiProvider: AiProvider,
 ) {
      return customInstance<TData>(
      {url: `/api/AiProviders`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aiProvider
    },
      this.http,
      );
    }
   getApiAiProvidersInactive<TData = AiProvider[]>(

 ) {
      return customInstance<TData>(
      {url: `/api/AiProviders/inactive`, method: 'GET'
    },
      this.http,
      );
    }
   getApiAiProvidersId<TData = AiProviderDTO>(
    id: number | string,
 ) {
      return customInstance<TData>(
      {url: `/api/AiProviders/${id}`, method: 'GET'
    },
      this.http,
      );
    }
   putApiAiProvidersId<TData = void>(
    id: number | string,
    aiProvider: AiProvider,
 ) {
      return customInstance<TData>(
      {url: `/api/AiProviders/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: aiProvider
    },
      this.http,
      );
    }
   deleteApiAiProvidersId<TData = void>(
    id: number | string,
 ) {
      return customInstance<TData>(
      {url: `/api/AiProviders/${id}`, method: 'DELETE'
    },
      this.http,
      );
    }
   getApiAiProvidersIdDiscoverModels<TData = AiModelMinimalDTO[]>(
    id: number | string,
 ) {
      return customInstance<TData>(
      {url: `/api/AiProviders/${id}/discover-models`, method: 'GET'
    },
      this.http,
      );
    }
   getApiAiProvidersHealth<TData = AiProviderHealthDTO>(
    params?: GetApiAiProvidersHealthParams,
 ) {
      return customInstance<TData>(
      {url: `/api/AiProviders/health`, method: 'GET',
        params: (() => {

  const filteredParams: Record<string, string | number | boolean | Array<string | number | boolean>> = {};
  for (const [key, value] of Object.entries(params ?? {})) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
})()
    },
      this.http,
      );
    }
   postApiAiProvidersIdHealth<TData = AiProviderHealthDTO>(
    id: number | string,
 ) {
      return customInstance<TData>(
      {url: `/api/AiProviders/${id}/health`, method: 'POST'
    },
      this.http,
      );
    }
  };

