/**
 * Generated by orval 🍺
 * Do not edit manually.
 * sloppr | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AiProviderDTO } from './aiProviderDTO';

export interface AiModelDTO {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  dateCreated?: string;
  dateUpdated?: string;
  isActive?: boolean;
  createdBy?: string;
  updatedBy?: string;
  name: string;
  identifier: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  aiProviderId?: number | string;
  aiProvider: AiProviderDTO;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  contextWindow?: number | string | null;
  /** @nullable */
  capabilities?: string | null;
}
