/**
 * Generated by orval 🍺
 * Do not edit manually.
 * sloppr | v1
 * OpenAPI spec version: 1.0.0
 */

export interface AiModelMinimalDTO {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  name: string;
  identifier: string;
  isActive?: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  aiProviderId?: number | string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  contextWindow?: number | string | null;
  /** @nullable */
  capabilities?: string | null;
}
