/**
 * Generated by orval 🍺
 * Do not edit manually.
 * sloppr | v1
 * OpenAPI spec version: 1.0.0
 */

export interface AiProviderHealthDTO {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  /** @nullable */
  isHealthy?: boolean | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  lastHealthStatusCode?: number | string | null;
  /** @nullable */
  lastHealthResponse?: string | null;
  /** @nullable */
  dateHealthChecked?: string | null;
}
