/**
 * Generated by orval 🍺
 * Do not edit manually.
 * sloppr | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AiProviderType } from './aiProviderType';

export interface AiProviderDTO {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  dateCreated?: string;
  dateUpdated?: string;
  isActive?: boolean;
  createdBy?: string;
  updatedBy?: string;
  name?: string;
  providerType?: AiProviderType;
  /** @nullable */
  baseUrl?: string | null;
  /** @nullable */
  isHealthy?: boolean | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  lastHealthStatusCode?: number | string | null;
  /** @nullable */
  lastHealthResponse?: string | null;
  /** @nullable */
  dateHealthChecked?: string | null;
}
