/**
 * Generated by orval 🍺
 * Do not edit manually.
 * sloppr | v1
 * OpenAPI spec version: 1.0.0
 */

export type AiProviderType = typeof AiProviderType[keyof typeof AiProviderType];


export const AiProviderType = {
  Ollama: 'Ollama',
  OpenAI: 'OpenAI',
  Anthropic: 'Anthropic',
} as const;
