/**
 * Generated by orval 🍺
 * Do not edit manually.
 * sloppr | v1
 * OpenAPI spec version: 1.0.0
 */

export interface KeyIngredient {
  name: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  numQueried?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  numUsed?: number | string;
  /** @nullable */
  lastUsed?: string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  dateCreated?: string;
  dateUpdated?: string;
  isActive?: boolean;
  isDeleted?: boolean;
  createdBy?: string;
  updatedBy?: string;
}
