/**
 * Generated by orval 🍺
 * Do not edit manually.
 * sloppr | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AiProviderType } from './aiProviderType';

export type PostApiChatChatParams = {
type?: AiProviderType;
prompt?: string;
};
