/**
 * Generated by orval 🍺
 * Do not edit manually.
 * sloppr | v1
 * OpenAPI spec version: 1.0.0
 */

export type PostApiChatChat2Params = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
modelId?: number | string;
};
